### ISSUE TITLE
Remove formatting from generated number

### ISSUE THREAD

**Issue by lwedgren** [jlattimer/CRM-Numeric-Workflow-Utilities#1]
It would be great to be able to remove the local number formatting from a randomly generated number, so that it could be used in a string for a unique identifier.

**Comment by jlattimer** [comment]
You could my String WF utilities to remove the non-numbers - the various replace functions will accept a number (the output of generate random) as input. 

https://github.com/jlattimer/CRM-String-Workflow-Utilities

**Comment by bedgren** [comment]
Worked perfect, thanks Jason!
